FROM caseylau/php:7.2-fpm-drupal-env

# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN echo "[xdebug]" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# install the PHP extensions we need
RUN apt-get update \
&& apt-get install -y git \
&& rm -rf /var/lib/apt/lists/* \
&& docker-php-ext-install bcmath

# install Composer globally
RUN curl -sS https://getcomposer.org/installer | php \
&& mv composer.phar /usr/local/bin/composer